'''Seq represents an extension of the "str" (string)
object type that is built into Python by supporting additional biologically
relevant methods like translate(), reverse_complement() and count()'''

from Bio.Seq import Seq
my_seq = Seq('''GGGAGGCTATCCTGTAAGACATCCTCTGCCGTTACAGCGCTCTTCCGTGATCAGCATTATGGAGTTCCTCTTAGACTATGATTCTACCCGTAAGGTGCAGCAGGAGCCATTAAGAAGGTCCGGTCTACGGAGCACAAATCGGT
             TAAAGCGAATAAAAGCTCCCACTGCACCCACCTCACCAGATGCATAGAGCCAGGCACAAAAGCTGCTGACGCTAGAGAGCTGCACTTTCTGGTCAAGTGAGATGAAATAGGTTAAAGTCTTTGACAGATGTTCGGATAGCATGAAAACGGACTGTTAGTGGTTTGATTGACTGGTTGCTGTCGCGCAACGGCACCGAAACACCTTTTAGCAGGGCCGCAAAATGC
             GCATATTCATGCGGAGCATTACTGTGTCCGCTGGCTAAAGCCCGATTCAATTATCAACCTCCTGTACTCTAGAGGCGTCTTCCATATGTATGACGATAGATCTCTCGGACCTTCATTCGGTCGAGAATTAAATTCGTGTTCTCGTGAATGCCTTGTGATGTTTTAAGGCGAATGCTAATTGATCGTCAACAGACAACGCGTTAGCCTCAAGCTGGTGTCGCCAGC
             TTTTACGCATCGCCCGCTGCCACATGGACTCTTGCTATTTACGTTCCGAATCACCAATTGTGAGACCACGGTCCAACTGTACACTCGGAACTTTACGAATGTTGTATGCACACGCGGTTTGCACGGCTTCCCACGCTTCCAATCGATCAGCCCGCAAATCGCCCCGTCATACTTTCAGCGCCTTAATCAGCTAGCGCCGTCTGAATAGACCGTGTGCGATATCCG
             TTCCCTGACCTGCGTCCCTAGAGAATAAAGTTGTACCAGCCA''')

nucleo = ['A','C','G','T']
for i in nucleo:
    print(my_seq.count(i), sep=' ', end=' ') #-> 214 227 199 220
